"""initial schema

Revision ID: e9500a2f54fe
Revises: 
Create Date: 2026-07-28 20:20:41.498073
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e9500a2f54fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('default_probability', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('category', sa.Enum('open', 'won', 'lost', name='stage_category', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('deal_type', sa.Enum('acquisition', 'disposition', 'development', 'debt', name='deal_type', native_enum=False), nullable=False),
    sa.Column('property_type', sa.Enum('multifamily', 'office', 'industrial', 'retail', 'hospitality', 'land', 'mixed_use', 'self_storage', 'other', name='property_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_hold', 'won', 'lost', name='deal_status', native_enum=False), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=12), nullable=True),
    sa.Column('market', sa.String(length=120), nullable=True),
    sa.Column('submarket', sa.String(length=120), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('noi', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('going_in_cap_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('stabilized_cap_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('target_irr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('target_equity_multiple', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('ltv', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('equity_required', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('date_sourced', sa.Date(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('broker', 'off_market', 'principal', 'referral', 'auction', 'other', name='deal_source', native_enum=False), nullable=True),
    sa.Column('broker_name', sa.String(length=120), nullable=True),
    sa.Column('broker_firm', sa.String(length=120), nullable=True),
    sa.Column('seller_name', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_market'), 'deals', ['market'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_id'), 'deals', ['stage_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('created', 'note', 'stage_change', 'field_change', 'task', 'milestone', 'document', 'team', name='activity_type', native_enum=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_deal_id'), 'activities', ['deal_id'], unique=False)
    op.create_table('deal_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_in_stage', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_history_deal_id'), 'deal_stage_history', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_stage_history_to_stage_id'), 'deal_stage_history', ['to_stage_id'], unique=False)
    op.create_table('deal_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'analyst', 'legal', 'capital_markets', 'asset_management', name='team_role', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'user_id', name='uq_deal_team_member')
    )
    op.create_index(op.f('ix_deal_team_members_deal_id'), 'deal_team_members', ['deal_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('om', 'rent_roll', 't12', 'psa', 'title', 'environmental', 'appraisal', 'survey', 'model', 'other', name='document_category', native_enum=False), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deal_id'), 'documents', ['deal_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_deal_id'), 'milestones', ['deal_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'blocked', name='task_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority', native_enum=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_deal_id'), 'tasks', ['deal_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deal_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_milestones_deal_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_documents_deal_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deal_team_members_deal_id'), table_name='deal_team_members')
    op.drop_table('deal_team_members')
    op.drop_index(op.f('ix_deal_stage_history_to_stage_id'), table_name='deal_stage_history')
    op.drop_index(op.f('ix_deal_stage_history_deal_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_index(op.f('ix_activities_deal_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_deals_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_market'), table_name='deals')
    op.drop_table('deals')
    op.drop_table('users')
    op.drop_table('stages')
    # ### end Alembic commands ###
